In [1]:
import numpy as np
print(np.__version__)

2.4.2


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x[0]) 

1


In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result)

[5 7 9]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
(5,)


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.shape)


[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)


In [19]:
arr = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
<class 'numpy.ndarray'>
(1, 3, 3)
9


In [18]:
data = np.array([1, 2, 3, 4, 5])
print("min value:", np.min(data))
print("max value:", np.max(data))
print("sum value:", np.sum(data))


min value: 1
max value: 5
sum value: 15


In [23]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[4, 5, 6]])
np.concatenate([a, b], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [24]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [28]:
np.reshape(a, shape=(1, 6), order='C')


array([[0, 1, 2, 3, 4, 5]])

In [29]:
a = np.array([1, 2,3, 4, 5,])
a.shape

(5,)

In [30]:
a2 = a[np.newaxis, :]
a2.shape

(1, 5)

In [31]:
row_vetor = a[np.newaxis, :]
row_vetor.shape

(1, 5)

In [32]:
col_vector = a[:, np.newaxis]
col_vector.shape

(5, 1)

In [33]:
a = np.expand_dims(a, axis=0)
a.shape

(1, 5)

In [37]:
data = np.array([1, 2, 3, 4, 5])
data[0]
data[1:3]
data[-3:]


array([3, 4, 5])

In [38]:
a = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
print(a[a<4])

[1 2 3]


In [42]:
five_up = (a>= 5)
print(a[five_up])

five_by_two = (a % 2 == 0) & (a >= 5)
print(a[five_by_two])

[5 6 7 8 9]
[6 8]


In [43]:
c = a [(a>2) & (a<9)]
print(c)

[3 4 5 6 7 8]


In [44]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.nonzero(a > 7)
print(b)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))


In [45]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:9]
arr1

array([4, 5, 6, 7, 8, 9])

In [46]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [48]:
np.vstack([a1, a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
arr = np.random.randint(1, 100, size=(5, 5, 10))
print("array shape:", arr.shape)

mid_element = arr[2, 2, 5]
print("Mid element:", mid_element)



array shape: (5, 5, 10)


In [59]:
arr = np .arange(5*5*10) . reshape(5,5,10)
print("3D matrixs")
print(arr)
middle_block = arr[2]
print("midle block element",middle_block)
element = arr[2,2,5:10]
print("Accessed Element",element)

3D matrixs
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]]

 [[ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]]

 [[150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 22

In [2]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[7, 8,9],[1, 2, 3]])

result = a * b
print(result)

[[ 7 16 27]
 [ 4 10 18]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr.reshape(2, 3)
print(arr2d)


[[1 2 3]
 [4 5 6]]


In [7]:
arr2 = np.array([[1, 2, 3], [7, 8, 9]])
result = arr2d * arr2
print(result)

[[ 1  4  9]
 [28 40 54]]


In [8]:
arr1d = np.arange(16)
arr2d = arr1d.reshape(1, 16)
result = np.multiply(arr1d, arr2d)
print(result)

[[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]]
