In [1]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create arrays

# Array A: 1D array
A = np.array([2,4,6,8,10,12,14,16,18,20])

# Array B: 3x3 zeros
B = np.zeros((3,3))

# Array C: 5 random integers between 1 and 100
C = np.random.randint(1,101,5)

# Array D: 10 evenly spaced numbers between 0 and 5
D = np.linspace(0,5,10)

# Print arrays
print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)

# Step 3: Properties of Array A
print("\n--- Array A Information ---")
print("Shape:", A.shape)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Dimensions:", A.ndim)

# Step 4: Operations on Array A
print("\n--- Operations on Array A ---")

# Reshape
A_reshaped = A.reshape(2,5)
print("Reshaped A (2x5):\n", A_reshaped)

# Max value and index
print("Max Value:", A.max())
print("Index of Max Value:", A.argmax())

# Min value and index
print("Min Value:", A.min())
print("Index of Min Value:", A.argmin())

# Step 5: Create Array E
E = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Access element at row 1 column 2
print("\nArray E:\n", E)
print("Element at row 1 column 2:", E[1,2])

Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [49 92 33 61 44]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

--- Array A Information ---
Shape: (10,)
Data Type: int64
Size: 10
Dimensions: 1

--- Operations on Array A ---
Reshaped A (2x5):
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max Value: 20
Index of Max Value: 9
Min Value: 2
Index of Min Value: 0

Array E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 column 2: 6
