ASSIGNMENT 1: NumPy Array Explorer

In [1]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create arrays

# Array A: 1D array
A = np.array([2,4,6,8,10,12,14,16,18,20])

# Array B: 3x3 zeros
B = np.zeros((3,3))

# Array C: 5 random integers between 1 and 100
C = np.random.randint(1,101,5)

# Array D: 10 evenly spaced numbers between 0 and 5
D = np.linspace(0,5,10)

# Print arrays
print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)

# Step 3: Properties of Array A
print("\n--- Array A Information ---")
print("Shape:", A.shape)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Dimensions:", A.ndim)

# Step 4: Operations on Array A
print("\n--- Operations on Array A ---")

# Reshape
A_reshaped = A.reshape(2,5)
print("Reshaped A (2x5):\n", A_reshaped)

# Max value and index
print("Max Value:", A.max())
print("Index of Max Value:", A.argmax())

# Min value and index
print("Min Value:", A.min())
print("Index of Min Value:", A.argmin())

# Step 5: Create Array E
E = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# Access element at row 1 column 2
print("\nArray E:\n", E)
print("Element at row 1 column 2:", E[1,2])

Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [95 22 51 57 35]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

--- Array A Information ---
Shape: (10,)
Data Type: int64
Size: 10
Dimensions: 1

--- Operations on Array A ---
Reshaped A (2x5):
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max Value: 20
Index of Max Value: 9
Min Value: 2
Index of Min Value: 0

Array E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 column 2: 6


ASSIGNMENT 2: NumPy Array Math Wizard

In [2]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Step 3: Arithmetic Operations
print("\nAddition:\n", arr1 + arr2)
print("\nSubtraction:\n", arr1 - arr2)
print("\nMultiplication:\n", arr1 * arr2)
print("\nDivision:\n", arr1 / arr2)

# Step 4: Broadcasting explanation
# Broadcasting means NumPy automatically expands the smaller array
# so operations can be performed element-wise.

# Step 5: Universal Functions
arr3 = np.array([1,4,9,16,25])

print("\nSquare Root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Sine:", np.sin(arr3))

# Step 6: Array operations
arr4 = np.array([[5,12,3],[8,2,7]])

print("\nArray 4:\n", arr4)
print("Sum of all elements:", np.sum(arr4))
print("Max in each column:", np.max(arr4, axis=0))
print("Min in each row:", np.min(arr4, axis=1))

# Step 7: Type Casting
arr1_float = arr1.astype(float)
print("\narr1 converted to float:\n", arr1_float)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [10 20 30]

Addition:
 [[11 22 33]
 [14 25 36]]

Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]

Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]

Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]

Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

Array 4:
 [[ 5 12  3]
 [ 8  2  7]]
Sum of all elements: 37
Max in each column: [ 8 12  7]
Min in each row: [3 2]

arr1 converted to float:
 [[1. 2. 3.]
 [4. 5. 6.]]
